### ISSUE TITLE
How do I get the coordinates away from the wall?

### ISSUE THREAD

**Issue by wojiaoz71** [Jnnshschl/AmeisenNavigation#3]
When using ameisennavigation server,If the coordinates are closer to the wall, it is easier to touch the wall when turning.
Is there a way to solve this problem?

**Comment by Jnnshschl** [comment]
You could try to tweak your navmesh settings, there should be a setting to increase the minimal edge distance. But keep in mind that it is going to increase it at doors to, the bot might not be able to walk through them if its set too high.

**Comment by hackjoe8** [comment]
May I ask where the minimum edge distance is set?

**Comment by Jnnshschl** [comment]
You need to set it in your navmesh export tool (TrinitCore mmap export tool).

**Comment by hackjoe8** [comment]
> You need to set it in your navmesh export tool (TrinitCore mmap export tool).

Thanks♪(･ω･)ﾉ
