### ISSUE TITLE
[WOTLK] Bug : Get Path.

### ISSUE THREAD

**Issue by Mecca21** [Jnnshschl/AmeisenNavigation#5]
Hello, i did what the discord said to do, get the mmaps, etc but for some reason when i use your getPath method but it keeps returning 0,0,0. these are the vectors i am using 
this problem happens in eastern kingsdom and when i tried using it to get a path to a npc in thunderbluff

` Vector3 start = new Vector3(9361.473f, -7041.952f, 18.32074f);
        Vector3 end = new Vector3(9124.827f, -7067.296f, 23.31561f);`

and i am using your getpath method 
`public static IEnumerable<Vector3> GetPath(MessageType msgType, int mapId, Vector3 start, Vector3 end, int flags)
    {
        try
        {
            return Client.IsConnected ? Client.Send((byte)msgType, (mapId, flags, start, end)).AsArray<Vector3>() : Array.Empty<Vector3>();
        }
        catch
        {
            return Array.Empty<Vector3>();
        }
    }`

**Comment by rarrr** [comment]
@Mecca21 Did you find a resolve in the end? Does it just not work with WOTLK?
